server:
  port: 8085

spring:
  application:
    name: notification-service
  config:
    import: "configserver:http://config-server:8888"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
