server:
  port: 8084

spring:
  application:
    name: payment-service
  config:
    import: "configserver:http://config-server:8888"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
